
version: 2

models:
  - name: stg_redcards_structured
    description: "Test on dupes of the primary key"
    columns:
      - name: nationality
        description: "The first name of each player"
        tests:
          - not_null
      - name: playername
        description: "The last name of each player"
        tests:
          - unique
          - not_null
      - name: yellow
        description: "Number of yellow cards amassed by each player"
        tests:
#          - dbt_expectations.expect_column_to_exist
          - not_null
      - name: red
        description: "Number of yellow cards amassed by each player"
        tests:
#          - dbt_expectations.expect_column_to_exist
          - not_null     
      - name: teamname
        description: "Number of yellow cards amassed by each player"
        tests:
#          - dbt_expectations.expect_column_to_exist
          - not_null          
