
version: 2

models:
  - name: DBTMODEL_PREMIERCARDS
    description: "Test on dupes of the primary key"
    columns:
      - name: FULLNAME
        description: "The first name of each player"
        tests:
          - unique
          - not_null
    tests:
      - dbt_utils.expression_is_true:
          expression: "sumcards > 0"
