
version: 2

models:
  - name: redcards_structured
    description: "Test on dupes of the primary key"
    columns:
      - name: firstname
        description: "The first name of each player"
        tests:
          - unique
          - not_null
      - name: lastname
        description: "The last name of each player"
        tests:
          - unique
          - not_null