
version: 2

models:
  - name: redcards_structured
    description: "Test on dupes of the primary key"
    columns:
      - name: firstname
        description: "The first name of each player"
        tests:
          - unique
          - not_null
      - name: lastname
        description: "The last name of each player"
        tests:
          - unique
          - not_null
  - name: yellow_agg
    description: "Takes a count of the number of yellow cards which have been levied, grouped by team"

metrics:
  - name: count_by_team
    label: Count by Team
    description: "Takes a count of the number of yellow cards which have been levied, grouped by team"
    model: ref('redcards_structured')

    calculation_method: count
    sql: YELLOW

    timestamp: LASTUPDATED
    time_grains: [day, week, month, quarter, year, all_time]

    dimensions:
      - TEAMNAME
