version: 2

sources:
  - name: redcards_structured
    database: "{{ env_var('target_database') }}"
    schema: "{{ env_var('target_schema') }}"
    tables:
      - name: "{{ env_var('target_table') }}"
        loaded_at_field: LASTUPDATED
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 5
            period: day
