version: 2

sources:
  - name: redcards_source
    database: "{{ env_var('target_database') }}"
    schema: "{{ env_var('target_schema') }}"
    tables:
      - name: STG_SPRING_PREMIERCARDS
        loaded_at_field: TIMESTAMP
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 5
            period: day
